# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/brightdust/cppProject/websrv/tl/websrv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/brightdust/cppProject/websrv/tl/websrv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brightdust/cppProject/websrv/tl/websrv/CMakeFiles /home/brightdust/cppProject/websrv/tl/websrv/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brightdust/cppProject/websrv/tl/websrv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

HTTP/src/html_file.o: HTTP/src/html_file.cpp.o

.PHONY : HTTP/src/html_file.o

# target to build an object file
HTTP/src/html_file.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/HTTP/src/html_file.cpp.o
.PHONY : HTTP/src/html_file.cpp.o

HTTP/src/html_file.i: HTTP/src/html_file.cpp.i

.PHONY : HTTP/src/html_file.i

# target to preprocess a source file
HTTP/src/html_file.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/HTTP/src/html_file.cpp.i
.PHONY : HTTP/src/html_file.cpp.i

HTTP/src/html_file.s: HTTP/src/html_file.cpp.s

.PHONY : HTTP/src/html_file.s

# target to generate assembly for a file
HTTP/src/html_file.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/HTTP/src/html_file.cpp.s
.PHONY : HTTP/src/html_file.cpp.s

HTTP/src/http_deal.o: HTTP/src/http_deal.cpp.o

.PHONY : HTTP/src/http_deal.o

# target to build an object file
HTTP/src/http_deal.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/HTTP/src/http_deal.cpp.o
.PHONY : HTTP/src/http_deal.cpp.o

HTTP/src/http_deal.i: HTTP/src/http_deal.cpp.i

.PHONY : HTTP/src/http_deal.i

# target to preprocess a source file
HTTP/src/http_deal.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/HTTP/src/http_deal.cpp.i
.PHONY : HTTP/src/http_deal.cpp.i

HTTP/src/http_deal.s: HTTP/src/http_deal.cpp.s

.PHONY : HTTP/src/http_deal.s

# target to generate assembly for a file
HTTP/src/http_deal.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/HTTP/src/http_deal.cpp.s
.PHONY : HTTP/src/http_deal.cpp.s

HTTP/src/http_message.o: HTTP/src/http_message.cpp.o

.PHONY : HTTP/src/http_message.o

# target to build an object file
HTTP/src/http_message.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/HTTP/src/http_message.cpp.o
.PHONY : HTTP/src/http_message.cpp.o

HTTP/src/http_message.i: HTTP/src/http_message.cpp.i

.PHONY : HTTP/src/http_message.i

# target to preprocess a source file
HTTP/src/http_message.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/HTTP/src/http_message.cpp.i
.PHONY : HTTP/src/http_message.cpp.i

HTTP/src/http_message.s: HTTP/src/http_message.cpp.s

.PHONY : HTTP/src/http_message.s

# target to generate assembly for a file
HTTP/src/http_message.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/HTTP/src/http_message.cpp.s
.PHONY : HTTP/src/http_message.cpp.s

HTTP/src/http_request.o: HTTP/src/http_request.cpp.o

.PHONY : HTTP/src/http_request.o

# target to build an object file
HTTP/src/http_request.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/HTTP/src/http_request.cpp.o
.PHONY : HTTP/src/http_request.cpp.o

HTTP/src/http_request.i: HTTP/src/http_request.cpp.i

.PHONY : HTTP/src/http_request.i

# target to preprocess a source file
HTTP/src/http_request.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/HTTP/src/http_request.cpp.i
.PHONY : HTTP/src/http_request.cpp.i

HTTP/src/http_request.s: HTTP/src/http_request.cpp.s

.PHONY : HTTP/src/http_request.s

# target to generate assembly for a file
HTTP/src/http_request.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/HTTP/src/http_request.cpp.s
.PHONY : HTTP/src/http_request.cpp.s

HTTP/src/http_server.o: HTTP/src/http_server.cpp.o

.PHONY : HTTP/src/http_server.o

# target to build an object file
HTTP/src/http_server.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/HTTP/src/http_server.cpp.o
.PHONY : HTTP/src/http_server.cpp.o

HTTP/src/http_server.i: HTTP/src/http_server.cpp.i

.PHONY : HTTP/src/http_server.i

# target to preprocess a source file
HTTP/src/http_server.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/HTTP/src/http_server.cpp.i
.PHONY : HTTP/src/http_server.cpp.i

HTTP/src/http_server.s: HTTP/src/http_server.cpp.s

.PHONY : HTTP/src/http_server.s

# target to generate assembly for a file
HTTP/src/http_server.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/HTTP/src/http_server.cpp.s
.PHONY : HTTP/src/http_server.cpp.s

TCP/src/tcp_acceptor.o: TCP/src/tcp_acceptor.cpp.o

.PHONY : TCP/src/tcp_acceptor.o

# target to build an object file
TCP/src/tcp_acceptor.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_acceptor.cpp.o
.PHONY : TCP/src/tcp_acceptor.cpp.o

TCP/src/tcp_acceptor.i: TCP/src/tcp_acceptor.cpp.i

.PHONY : TCP/src/tcp_acceptor.i

# target to preprocess a source file
TCP/src/tcp_acceptor.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_acceptor.cpp.i
.PHONY : TCP/src/tcp_acceptor.cpp.i

TCP/src/tcp_acceptor.s: TCP/src/tcp_acceptor.cpp.s

.PHONY : TCP/src/tcp_acceptor.s

# target to generate assembly for a file
TCP/src/tcp_acceptor.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_acceptor.cpp.s
.PHONY : TCP/src/tcp_acceptor.cpp.s

TCP/src/tcp_acceptor_epoll.o: TCP/src/tcp_acceptor_epoll.cpp.o

.PHONY : TCP/src/tcp_acceptor_epoll.o

# target to build an object file
TCP/src/tcp_acceptor_epoll.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_acceptor_epoll.cpp.o
.PHONY : TCP/src/tcp_acceptor_epoll.cpp.o

TCP/src/tcp_acceptor_epoll.i: TCP/src/tcp_acceptor_epoll.cpp.i

.PHONY : TCP/src/tcp_acceptor_epoll.i

# target to preprocess a source file
TCP/src/tcp_acceptor_epoll.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_acceptor_epoll.cpp.i
.PHONY : TCP/src/tcp_acceptor_epoll.cpp.i

TCP/src/tcp_acceptor_epoll.s: TCP/src/tcp_acceptor_epoll.cpp.s

.PHONY : TCP/src/tcp_acceptor_epoll.s

# target to generate assembly for a file
TCP/src/tcp_acceptor_epoll.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_acceptor_epoll.cpp.s
.PHONY : TCP/src/tcp_acceptor_epoll.cpp.s

TCP/src/tcp_buff_pool.o: TCP/src/tcp_buff_pool.cpp.o

.PHONY : TCP/src/tcp_buff_pool.o

# target to build an object file
TCP/src/tcp_buff_pool.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_buff_pool.cpp.o
.PHONY : TCP/src/tcp_buff_pool.cpp.o

TCP/src/tcp_buff_pool.i: TCP/src/tcp_buff_pool.cpp.i

.PHONY : TCP/src/tcp_buff_pool.i

# target to preprocess a source file
TCP/src/tcp_buff_pool.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_buff_pool.cpp.i
.PHONY : TCP/src/tcp_buff_pool.cpp.i

TCP/src/tcp_buff_pool.s: TCP/src/tcp_buff_pool.cpp.s

.PHONY : TCP/src/tcp_buff_pool.s

# target to generate assembly for a file
TCP/src/tcp_buff_pool.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_buff_pool.cpp.s
.PHONY : TCP/src/tcp_buff_pool.cpp.s

TCP/src/tcp_buffer.o: TCP/src/tcp_buffer.cpp.o

.PHONY : TCP/src/tcp_buffer.o

# target to build an object file
TCP/src/tcp_buffer.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_buffer.cpp.o
.PHONY : TCP/src/tcp_buffer.cpp.o

TCP/src/tcp_buffer.i: TCP/src/tcp_buffer.cpp.i

.PHONY : TCP/src/tcp_buffer.i

# target to preprocess a source file
TCP/src/tcp_buffer.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_buffer.cpp.i
.PHONY : TCP/src/tcp_buffer.cpp.i

TCP/src/tcp_buffer.s: TCP/src/tcp_buffer.cpp.s

.PHONY : TCP/src/tcp_buffer.s

# target to generate assembly for a file
TCP/src/tcp_buffer.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_buffer.cpp.s
.PHONY : TCP/src/tcp_buffer.cpp.s

TCP/src/tcp_channel.o: TCP/src/tcp_channel.cpp.o

.PHONY : TCP/src/tcp_channel.o

# target to build an object file
TCP/src/tcp_channel.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_channel.cpp.o
.PHONY : TCP/src/tcp_channel.cpp.o

TCP/src/tcp_channel.i: TCP/src/tcp_channel.cpp.i

.PHONY : TCP/src/tcp_channel.i

# target to preprocess a source file
TCP/src/tcp_channel.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_channel.cpp.i
.PHONY : TCP/src/tcp_channel.cpp.i

TCP/src/tcp_channel.s: TCP/src/tcp_channel.cpp.s

.PHONY : TCP/src/tcp_channel.s

# target to generate assembly for a file
TCP/src/tcp_channel.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_channel.cpp.s
.PHONY : TCP/src/tcp_channel.cpp.s

TCP/src/tcp_connect.o: TCP/src/tcp_connect.cpp.o

.PHONY : TCP/src/tcp_connect.o

# target to build an object file
TCP/src/tcp_connect.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_connect.cpp.o
.PHONY : TCP/src/tcp_connect.cpp.o

TCP/src/tcp_connect.i: TCP/src/tcp_connect.cpp.i

.PHONY : TCP/src/tcp_connect.i

# target to preprocess a source file
TCP/src/tcp_connect.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_connect.cpp.i
.PHONY : TCP/src/tcp_connect.cpp.i

TCP/src/tcp_connect.s: TCP/src/tcp_connect.cpp.s

.PHONY : TCP/src/tcp_connect.s

# target to generate assembly for a file
TCP/src/tcp_connect.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_connect.cpp.s
.PHONY : TCP/src/tcp_connect.cpp.s

TCP/src/tcp_server.o: TCP/src/tcp_server.cpp.o

.PHONY : TCP/src/tcp_server.o

# target to build an object file
TCP/src/tcp_server.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_server.cpp.o
.PHONY : TCP/src/tcp_server.cpp.o

TCP/src/tcp_server.i: TCP/src/tcp_server.cpp.i

.PHONY : TCP/src/tcp_server.i

# target to preprocess a source file
TCP/src/tcp_server.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_server.cpp.i
.PHONY : TCP/src/tcp_server.cpp.i

TCP/src/tcp_server.s: TCP/src/tcp_server.cpp.s

.PHONY : TCP/src/tcp_server.s

# target to generate assembly for a file
TCP/src/tcp_server.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_server.cpp.s
.PHONY : TCP/src/tcp_server.cpp.s

TCP/src/tcp_thread_pool.o: TCP/src/tcp_thread_pool.cpp.o

.PHONY : TCP/src/tcp_thread_pool.o

# target to build an object file
TCP/src/tcp_thread_pool.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_thread_pool.cpp.o
.PHONY : TCP/src/tcp_thread_pool.cpp.o

TCP/src/tcp_thread_pool.i: TCP/src/tcp_thread_pool.cpp.i

.PHONY : TCP/src/tcp_thread_pool.i

# target to preprocess a source file
TCP/src/tcp_thread_pool.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_thread_pool.cpp.i
.PHONY : TCP/src/tcp_thread_pool.cpp.i

TCP/src/tcp_thread_pool.s: TCP/src/tcp_thread_pool.cpp.s

.PHONY : TCP/src/tcp_thread_pool.s

# target to generate assembly for a file
TCP/src/tcp_thread_pool.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_thread_pool.cpp.s
.PHONY : TCP/src/tcp_thread_pool.cpp.s

TCP/src/tcp_thread_pool_process.o: TCP/src/tcp_thread_pool_process.cpp.o

.PHONY : TCP/src/tcp_thread_pool_process.o

# target to build an object file
TCP/src/tcp_thread_pool_process.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_thread_pool_process.cpp.o
.PHONY : TCP/src/tcp_thread_pool_process.cpp.o

TCP/src/tcp_thread_pool_process.i: TCP/src/tcp_thread_pool_process.cpp.i

.PHONY : TCP/src/tcp_thread_pool_process.i

# target to preprocess a source file
TCP/src/tcp_thread_pool_process.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_thread_pool_process.cpp.i
.PHONY : TCP/src/tcp_thread_pool_process.cpp.i

TCP/src/tcp_thread_pool_process.s: TCP/src/tcp_thread_pool_process.cpp.s

.PHONY : TCP/src/tcp_thread_pool_process.s

# target to generate assembly for a file
TCP/src/tcp_thread_pool_process.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/TCP/src/tcp_thread_pool_process.cpp.s
.PHONY : TCP/src/tcp_thread_pool_process.cpp.s

base/src/file_read.o: base/src/file_read.cpp.o

.PHONY : base/src/file_read.o

# target to build an object file
base/src/file_read.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/base/src/file_read.cpp.o
.PHONY : base/src/file_read.cpp.o

base/src/file_read.i: base/src/file_read.cpp.i

.PHONY : base/src/file_read.i

# target to preprocess a source file
base/src/file_read.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/base/src/file_read.cpp.i
.PHONY : base/src/file_read.cpp.i

base/src/file_read.s: base/src/file_read.cpp.s

.PHONY : base/src/file_read.s

# target to generate assembly for a file
base/src/file_read.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/base/src/file_read.cpp.s
.PHONY : base/src/file_read.cpp.s

base/src/local_message.o: base/src/local_message.cpp.o

.PHONY : base/src/local_message.o

# target to build an object file
base/src/local_message.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/base/src/local_message.cpp.o
.PHONY : base/src/local_message.cpp.o

base/src/local_message.i: base/src/local_message.cpp.i

.PHONY : base/src/local_message.i

# target to preprocess a source file
base/src/local_message.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/base/src/local_message.cpp.i
.PHONY : base/src/local_message.cpp.i

base/src/local_message.s: base/src/local_message.cpp.s

.PHONY : base/src/local_message.s

# target to generate assembly for a file
base/src/local_message.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/base/src/local_message.cpp.s
.PHONY : base/src/local_message.cpp.s

base/src/safe_queue.o: base/src/safe_queue.cpp.o

.PHONY : base/src/safe_queue.o

# target to build an object file
base/src/safe_queue.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/base/src/safe_queue.cpp.o
.PHONY : base/src/safe_queue.cpp.o

base/src/safe_queue.i: base/src/safe_queue.cpp.i

.PHONY : base/src/safe_queue.i

# target to preprocess a source file
base/src/safe_queue.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/base/src/safe_queue.cpp.i
.PHONY : base/src/safe_queue.cpp.i

base/src/safe_queue.s: base/src/safe_queue.cpp.s

.PHONY : base/src/safe_queue.s

# target to generate assembly for a file
base/src/safe_queue.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/base/src/safe_queue.cpp.s
.PHONY : base/src/safe_queue.cpp.s

log/src/log_buffer.o: log/src/log_buffer.cpp.o

.PHONY : log/src/log_buffer.o

# target to build an object file
log/src/log_buffer.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/log/src/log_buffer.cpp.o
.PHONY : log/src/log_buffer.cpp.o

log/src/log_buffer.i: log/src/log_buffer.cpp.i

.PHONY : log/src/log_buffer.i

# target to preprocess a source file
log/src/log_buffer.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/log/src/log_buffer.cpp.i
.PHONY : log/src/log_buffer.cpp.i

log/src/log_buffer.s: log/src/log_buffer.cpp.s

.PHONY : log/src/log_buffer.s

# target to generate assembly for a file
log/src/log_buffer.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/log/src/log_buffer.cpp.s
.PHONY : log/src/log_buffer.cpp.s

log/src/log_file.o: log/src/log_file.cpp.o

.PHONY : log/src/log_file.o

# target to build an object file
log/src/log_file.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/log/src/log_file.cpp.o
.PHONY : log/src/log_file.cpp.o

log/src/log_file.i: log/src/log_file.cpp.i

.PHONY : log/src/log_file.i

# target to preprocess a source file
log/src/log_file.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/log/src/log_file.cpp.i
.PHONY : log/src/log_file.cpp.i

log/src/log_file.s: log/src/log_file.cpp.s

.PHONY : log/src/log_file.s

# target to generate assembly for a file
log/src/log_file.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/log/src/log_file.cpp.s
.PHONY : log/src/log_file.cpp.s

log/src/log_stream.o: log/src/log_stream.cpp.o

.PHONY : log/src/log_stream.o

# target to build an object file
log/src/log_stream.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/log/src/log_stream.cpp.o
.PHONY : log/src/log_stream.cpp.o

log/src/log_stream.i: log/src/log_stream.cpp.i

.PHONY : log/src/log_stream.i

# target to preprocess a source file
log/src/log_stream.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/log/src/log_stream.cpp.i
.PHONY : log/src/log_stream.cpp.i

log/src/log_stream.s: log/src/log_stream.cpp.s

.PHONY : log/src/log_stream.s

# target to generate assembly for a file
log/src/log_stream.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/log/src/log_stream.cpp.s
.PHONY : log/src/log_stream.cpp.s

log/src/log_thread.o: log/src/log_thread.cpp.o

.PHONY : log/src/log_thread.o

# target to build an object file
log/src/log_thread.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/log/src/log_thread.cpp.o
.PHONY : log/src/log_thread.cpp.o

log/src/log_thread.i: log/src/log_thread.cpp.i

.PHONY : log/src/log_thread.i

# target to preprocess a source file
log/src/log_thread.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/log/src/log_thread.cpp.i
.PHONY : log/src/log_thread.cpp.i

log/src/log_thread.s: log/src/log_thread.cpp.s

.PHONY : log/src/log_thread.s

# target to generate assembly for a file
log/src/log_thread.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/log/src/log_thread.cpp.s
.PHONY : log/src/log_thread.cpp.s

log/src/logger.o: log/src/logger.cpp.o

.PHONY : log/src/logger.o

# target to build an object file
log/src/logger.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/log/src/logger.cpp.o
.PHONY : log/src/logger.cpp.o

log/src/logger.i: log/src/logger.cpp.i

.PHONY : log/src/logger.i

# target to preprocess a source file
log/src/logger.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/log/src/logger.cpp.i
.PHONY : log/src/logger.cpp.i

log/src/logger.s: log/src/logger.cpp.s

.PHONY : log/src/logger.s

# target to generate assembly for a file
log/src/logger.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/log/src/logger.cpp.s
.PHONY : log/src/logger.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/main.cpp.s
.PHONY : main.cpp.s

mysql/src/mysql_buf.o: mysql/src/mysql_buf.cpp.o

.PHONY : mysql/src/mysql_buf.o

# target to build an object file
mysql/src/mysql_buf.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/mysql/src/mysql_buf.cpp.o
.PHONY : mysql/src/mysql_buf.cpp.o

mysql/src/mysql_buf.i: mysql/src/mysql_buf.cpp.i

.PHONY : mysql/src/mysql_buf.i

# target to preprocess a source file
mysql/src/mysql_buf.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/mysql/src/mysql_buf.cpp.i
.PHONY : mysql/src/mysql_buf.cpp.i

mysql/src/mysql_buf.s: mysql/src/mysql_buf.cpp.s

.PHONY : mysql/src/mysql_buf.s

# target to generate assembly for a file
mysql/src/mysql_buf.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/mysql/src/mysql_buf.cpp.s
.PHONY : mysql/src/mysql_buf.cpp.s

mysql/src/mysql_conn.o: mysql/src/mysql_conn.cpp.o

.PHONY : mysql/src/mysql_conn.o

# target to build an object file
mysql/src/mysql_conn.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/mysql/src/mysql_conn.cpp.o
.PHONY : mysql/src/mysql_conn.cpp.o

mysql/src/mysql_conn.i: mysql/src/mysql_conn.cpp.i

.PHONY : mysql/src/mysql_conn.i

# target to preprocess a source file
mysql/src/mysql_conn.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/mysql/src/mysql_conn.cpp.i
.PHONY : mysql/src/mysql_conn.cpp.i

mysql/src/mysql_conn.s: mysql/src/mysql_conn.cpp.s

.PHONY : mysql/src/mysql_conn.s

# target to generate assembly for a file
mysql/src/mysql_conn.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/mysql/src/mysql_conn.cpp.s
.PHONY : mysql/src/mysql_conn.cpp.s

time/src/time_point.o: time/src/time_point.cpp.o

.PHONY : time/src/time_point.o

# target to build an object file
time/src/time_point.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/time/src/time_point.cpp.o
.PHONY : time/src/time_point.cpp.o

time/src/time_point.i: time/src/time_point.cpp.i

.PHONY : time/src/time_point.i

# target to preprocess a source file
time/src/time_point.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/time/src/time_point.cpp.i
.PHONY : time/src/time_point.cpp.i

time/src/time_point.s: time/src/time_point.cpp.s

.PHONY : time/src/time_point.s

# target to generate assembly for a file
time/src/time_point.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/time/src/time_point.cpp.s
.PHONY : time/src/time_point.cpp.s

time/src/timmer.o: time/src/timmer.cpp.o

.PHONY : time/src/timmer.o

# target to build an object file
time/src/timmer.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/time/src/timmer.cpp.o
.PHONY : time/src/timmer.cpp.o

time/src/timmer.i: time/src/timmer.cpp.i

.PHONY : time/src/timmer.i

# target to preprocess a source file
time/src/timmer.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/time/src/timmer.cpp.i
.PHONY : time/src/timmer.cpp.i

time/src/timmer.s: time/src/timmer.cpp.s

.PHONY : time/src/timmer.s

# target to generate assembly for a file
time/src/timmer.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/time/src/timmer.cpp.s
.PHONY : time/src/timmer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... HTTP/src/html_file.o"
	@echo "... HTTP/src/html_file.i"
	@echo "... HTTP/src/html_file.s"
	@echo "... HTTP/src/http_deal.o"
	@echo "... HTTP/src/http_deal.i"
	@echo "... HTTP/src/http_deal.s"
	@echo "... HTTP/src/http_message.o"
	@echo "... HTTP/src/http_message.i"
	@echo "... HTTP/src/http_message.s"
	@echo "... HTTP/src/http_request.o"
	@echo "... HTTP/src/http_request.i"
	@echo "... HTTP/src/http_request.s"
	@echo "... HTTP/src/http_server.o"
	@echo "... HTTP/src/http_server.i"
	@echo "... HTTP/src/http_server.s"
	@echo "... TCP/src/tcp_acceptor.o"
	@echo "... TCP/src/tcp_acceptor.i"
	@echo "... TCP/src/tcp_acceptor.s"
	@echo "... TCP/src/tcp_acceptor_epoll.o"
	@echo "... TCP/src/tcp_acceptor_epoll.i"
	@echo "... TCP/src/tcp_acceptor_epoll.s"
	@echo "... TCP/src/tcp_buff_pool.o"
	@echo "... TCP/src/tcp_buff_pool.i"
	@echo "... TCP/src/tcp_buff_pool.s"
	@echo "... TCP/src/tcp_buffer.o"
	@echo "... TCP/src/tcp_buffer.i"
	@echo "... TCP/src/tcp_buffer.s"
	@echo "... TCP/src/tcp_channel.o"
	@echo "... TCP/src/tcp_channel.i"
	@echo "... TCP/src/tcp_channel.s"
	@echo "... TCP/src/tcp_connect.o"
	@echo "... TCP/src/tcp_connect.i"
	@echo "... TCP/src/tcp_connect.s"
	@echo "... TCP/src/tcp_server.o"
	@echo "... TCP/src/tcp_server.i"
	@echo "... TCP/src/tcp_server.s"
	@echo "... TCP/src/tcp_thread_pool.o"
	@echo "... TCP/src/tcp_thread_pool.i"
	@echo "... TCP/src/tcp_thread_pool.s"
	@echo "... TCP/src/tcp_thread_pool_process.o"
	@echo "... TCP/src/tcp_thread_pool_process.i"
	@echo "... TCP/src/tcp_thread_pool_process.s"
	@echo "... base/src/file_read.o"
	@echo "... base/src/file_read.i"
	@echo "... base/src/file_read.s"
	@echo "... base/src/local_message.o"
	@echo "... base/src/local_message.i"
	@echo "... base/src/local_message.s"
	@echo "... base/src/safe_queue.o"
	@echo "... base/src/safe_queue.i"
	@echo "... base/src/safe_queue.s"
	@echo "... log/src/log_buffer.o"
	@echo "... log/src/log_buffer.i"
	@echo "... log/src/log_buffer.s"
	@echo "... log/src/log_file.o"
	@echo "... log/src/log_file.i"
	@echo "... log/src/log_file.s"
	@echo "... log/src/log_stream.o"
	@echo "... log/src/log_stream.i"
	@echo "... log/src/log_stream.s"
	@echo "... log/src/log_thread.o"
	@echo "... log/src/log_thread.i"
	@echo "... log/src/log_thread.s"
	@echo "... log/src/logger.o"
	@echo "... log/src/logger.i"
	@echo "... log/src/logger.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mysql/src/mysql_buf.o"
	@echo "... mysql/src/mysql_buf.i"
	@echo "... mysql/src/mysql_buf.s"
	@echo "... mysql/src/mysql_conn.o"
	@echo "... mysql/src/mysql_conn.i"
	@echo "... mysql/src/mysql_conn.s"
	@echo "... time/src/time_point.o"
	@echo "... time/src/time_point.i"
	@echo "... time/src/time_point.s"
	@echo "... time/src/timmer.o"
	@echo "... time/src/timmer.i"
	@echo "... time/src/timmer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

